Header component
React-Bootcamp-WoMarkersCode/call-of-papers pull request #20
Opened 2020-03-17 23:46 UTC by IsabellaSoares

2020-03-18 21:57 UTC, GabrieleSuzart requested changes
Dá uma revisada na identação de todo o código e nas classes css obsoletas =)

Ahh uma dica, add o arquivo como o https://github.com/GabrieleSuzart/workshop-react/blob/master/.editorconfig na raiz do projeto e instala o plugin "EditorConfig for VS Code"

2020-03-18 21:57 UTC, GabrieleSuzart commented on call-of-papers/src/App.js
> +	return (
Oi, a identação ficou meio zoada?

Dá uma olhadinha nesse artigo https://phpmz.home.blog/2019/06/17/o-que-e-indentacao-de-codigo-qual-e-sua-importancia/

2020-03-18 21:57 UTC, GabrieleSuzart commented on call-of-papers/src/App.js
> +			<Content className="App">
Precisa mesmo desse `className="App` ?
className é quando criamos uma classe css para estilizar, como você está usando o antd nesse bloco provavelmente não é necessário

2020-03-19 15:16 UTC, GabrieleSuzart requested changes
Precisa corrigir a identação do código

2020-03-20 01:20 UTC, IsabellaSoares commented on call-of-papers/src/App.js
> +	return (
Corrigido! 😄

2020-03-20 01:24 UTC, IsabellaSoares commented on call-of-papers/src/App.js
> +			<Content className="App">
Entendi! Muito obrigada pela dica!

2020-03-20 14:26 UTC, GabrieleSuzart commented on call-of-papers/src/components/Menu/index.js
> +    let history = useHistory();
Algumas identações acabou passando haha

2020-03-20 14:26 UTC, GabrieleSuzart approved these changes
O PR evoluiu muito parabéns =)

2020-03-20 14:26 UTC, merged