Telas submission
React-Bootcamp-WoMarkersCode/call-of-papers pull request #202
Opened 2020-04-22 19:46 UTC by oliviaresende

# Bloqueio área submission

## Descrição do PR

Área submission liberada apenas para o owner do evento

## Capturas de Tela

### Owner evento
![image](https://user-images.githubusercontent.com/60545426/80026527-a678b980-84b8-11ea-931f-e159ffe50618.png)

### Outros
![image](https://user-images.githubusercontent.com/60545426/80026569-b7c1c600-84b8-11ea-87db-c3024ba2a040.png)

## Issue do repo

Issue #193 

## Casos de Teste Pensados

- [x] Testei o uso para o owner e para outros usuarios.

2020-04-22 21:13 UTC, GabrieleSuzart commented on src/pages/Events/Event.js
> +import { copyToCliboard } from '../../utils/copyToCliboard'
Booooooooa!!!

2020-04-22 21:16 UTC, GabrieleSuzart commented on src/utils/copyToCliboard.js
> +    text = window.location.href
Se precisar para copiar outra informação no futuro, é só tirar essa linha e pegar o text por parametro

2020-04-22 21:23 UTC, GabrieleSuzart submitted a review, later dismissed

2020-04-22 21:23 UTC, GabrieleSuzart commented on src/pages/Submissions/SubmissionsTable.js
> +                  <FontAwesomeIcon icon={faLink} />Copiar link para Call of Papers
a identaçãoo dessa linha  85 e 86 tá errada, precisa 1 tab para dentro

2020-04-22 21:23 UTC, GabrieleSuzart commented on src/pages/Submissions/SubmissionsTable.js
> +                  <p>Quando os palestrantes submeterem as palestas, você poderá gerenciá-las aqui.</p>
Essa mensagem tem que colocar no index (pq se tiver palestras em analise isso não pode aparecer)

2020-04-22 21:23 UTC, GabrieleSuzart commented on src/pages/Submissions/index.js
> +          <>
aqui dentro você poe outra validação
lectures.lenght > 0 ? (exibe componentes) : (exibe aquela mensagem)

2020-04-22 21:30 UTC, GabrieleSuzart commented on src/pages/Submissions/index.js
> +          <>
independete do status

2020-04-22 21:32 UTC, oliviaresende commented on src/utils/copyToCliboard.js
> +    text = window.location.href
Ajustado

2020-04-22 21:32 UTC, oliviaresende commented on src/pages/Submissions/index.js
> +          <>
Ok

2020-04-22 21:33 UTC, oliviaresende commented on src/pages/Submissions/SubmissionsTable.js
> +                  <p>Quando os palestrantes submeterem as palestas, você poderá gerenciá-las aqui.</p>
ok

2020-04-22 21:33 UTC, GabrieleSuzart commented on src/pages/Submissions/SubmissionsTable.js
> +                  <p>Quando os palestrantes submeterem as palestas, você poderá gerenciá-las aqui.</p>
você mantem a validaçao que tem aqui, mas coloca apenas um `''` para não exibir nada

2020-04-23 01:11 UTC, GabrieleSuzart requested changes

2020-04-23 01:11 UTC, GabrieleSuzart commented on src/pages/Submissions/index.js
> +                  </Button>
identação...

2020-04-23 01:11 UTC, GabrieleSuzart commented on src/pages/Submissions/index.js
> +            <SubmissionsPending lectures={lecturesPending} handleUpdateLecture={handleUpdateLecture} />
Essa linha aqui sobe, fica dentro da mesma condição que o SubmissionsTable
```
(
<>
   <SubmissionsTable>
   <SubmissionsPending>
</>
)
```

2020-04-23 02:29 UTC, IsabellaSoares approved these changes

2020-04-23 02:38 UTC, lalizita approved these changes

2020-04-23 02:56 UTC, merged